# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d7bbab7a465033c7dd90dd7ac140476d709566f0e68f4a9fa16628bbed1913534b67e17fced1a9b9440911c08db5f10d01234699d5f509e5f42ecd51fe63d9d

test:
  secret_key_base: 4cfe5a6e144be815427cd5c2628fad3c15af8507325f3552647916a43cca80a9f3a5e085382095bd5e91c7d5017740a0104a8e52e07bc72e5db61114b52ddbd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
